### ISSUE TITLE
Unicode completion of suffix first, with exact matches low priority

### ISSUE THREAD

**Issue by aaron-jack-manning** [estin/simple-completion-language-server#146]
This is possibly related to #50, but the issue is present for me in the case of Unicode completion.

I have Unicode completion set up for various mathematical symbols but it generally very hard to get the symbol I am after, even when the source text has an exact match to the symbol name.

For instance, if I type `in` I get completions for symbol names beginning with `in` (such as `integral`) before the symbol which is just called `in`.

![Image](https://github.com/user-attachments/assets/e19e5f10-078c-4074-ad16-a09b98ec5464) ![Image](https://github.com/user-attachments/assets/41bace56-d2ee-46c0-b1d2-ec250659a6e9)

The same thing happens with suffixes, where I have an exact match typed in the buffer, but a partial match to the end of the word I am after is included and higher in the completion list.

![Image](https://github.com/user-attachments/assets/4180232d-4f5c-4096-b124-5290cb7c89fc) ![Image](https://github.com/user-attachments/assets/ed8d7da1-7ddb-4b2e-b1b6-49e21ff777c8)

**Comment by aaron-jack-manning** [comment]
> and works only with unicode-input

I'm not sure I fully understand what you mean by this. My goal with this is only to do unicode completion, my previous configuration was

```toml
[language-server.scls.config]
feature_unicode_input = true
```

and changing this to

```toml
[language-server.scls.config]
snippets_inline_by_word_tail = false
feature_unicode_input = true
```

or

```toml
[language-server.scls.config]
feature_snippets = true
snippets_first = true
snippets_inline_by_word_tail = false
feature_unicode_input = true
```

doesn't resolve the issue.
