### ISSUE TITLE
need help external snippets

### ISSUE THREAD

**Issue by DinkyTrady** [estin/simple-completion-language-server#18]
I'm still confused how to install with git repos

### Code on languages.toml
```toml
[language-server.scls]
command = "simple-completion-language-server"
config = { max_completion_items = 20, snippets_first = false }

[language-server.tsserver]
command = "typescript-language-server"
args = ["--stdio"]

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[[language]]
name = "javascript"
language-servers = [ "scls", "tsserver", "eslint" ]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
language-servers = [ "scls", "tsserver", "eslint" ]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[language-server.html-lsp]
command = "vscode-html-language-server"
args = ["--stdio"]

[[language]]
name = "html"
language-servers = [ "scls", "html-lsp", "emmet-lsp" ]
formatter = { command = "prettier", args = ["--parser", "html"] }
auto-format = true

[language-server.css-lsp]
command = "vscode-css-language-server"
args = ["--stdio"]

[[language]]
name = "css"
language-servers = [ "scls", "html-lsp", "emmet-lsp" ]
formatter = { command = "prettier", args = ["--parser", "css"] }
auto-format = true

[language-server.json-lsp]
command = "vscode-json-language-server"
args = ["--stdio"]

[[language]]
name = "json"
language-servers = [ "scls", "html-lsp" ]
formatter = { command = "prettier", args = ["--parser", "json"] }
auto-format = true
```
### Code on external-snippets.toml
```toml
[[sources]]
name = "friendly-snippets"
git = "https://github.com/rafamadriz/friemdly-snippets.git"
```

When i want to install it give error:
```bash
~ $ simple-completion-language-server fetch-external-snippets
2023-11-20T14:06:41.034313Z  INFO simple_completion_language_server: Try read config from: "/data/data/com.termux/files/home/.config/helix/external-snippets.toml"
thread 'main' panicked at src/main.rs:146:22:
Failed to fetch external snippets: TOML parse error at line 1, column 1
  |
1 | [[sources]]
  | ^^^^^^^^^^^
missing field `paths`

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by estin** [comment]
my current config for external snippets (pick some python snippets and whole rust snippets)
 
 ```toml
[[sources]] 
name = "friendly-snippets"
git = "https://github.com/rafamadriz/friendly-snippets.git"

[[sources.paths]]
scope = ["python"]
path = "snippets/python/base.json"

[[sources.paths]]
scope = ["python"]
path = "snippets/python/python.json"

[[sources.paths]]
scope = ["python"]
path = "snippets/python/unittest.json"

[[sources.paths]]
scope = ["rust"]
path = "snippets/rust/rust.json"
```
