### ISSUE TITLE
Collection of snippets

### ISSUE THREAD

**Issue by hnorkowski** [estin/simple-completion-language-server#4]
It would be nice to have a place to collect useful snippets so not everyone has to reinvent the wheel.

**Comment by estin** [comment]
Hi!
I don't want introduce new formats or standards and don't know to resolve task `collect useful snippets`...

Some one introduce snippets managers https://github.com/skewballfox/sniper

Others collect hire snippets https://github.com/ults-io/vscode-react-javascript-snippets/blob/master/src/snippets/generated.json and publish it on market places

May be best solution here is some adapters/clients to other formats/standards/managers

**Comment by hnorkowski** [comment]
Yeah I think adapters would also be a great solution. Overall I just think its important to at least give new users a hint where they can get a collection of snippets from.

**Comment by estin** [comment]
Hm...

We can improve current project and add  cli to git clone vscode extension.

For example. Add configuration file like that

```toml
[[repo]]
git = "<link to git repo with snippets>"

[[repo.snippets]]
scope = "<scope>"
path = "<path to snippets relative to repo path>"
format = "<some snippets format choice: toml1/toml2/vscode/texmate>"
```

and then
```bash
$ simple-completion-language-server install-snippets
> git clone <repo> ~/.config/helix/scls/<repo>

$ simple-completion-language-server update-snippets
> git clone or git pull
```

And user case may be
 - search vscode snippets on market https://marketplace.visualstudio.com/search?target=VSCode&category=Snippets&sortBy=Installs
 - find repo and configure scls
 - run command to install them
 - profit. only git + scls and you're have vscode snippets in basic support

Or choose one of https://github.com/rafamadriz/friendly-snippets

Sorry for my poor English.
