### ISSUE TITLE
Unable to setup scls

### ISSUE THREAD

**Issue by pix303** [estin/simple-completion-language-server#6]
Hi, in order to setup scls i have
1. update Helix to 23.10 to support muliple language server
2. setup language.toml as

```toml
[language-server.scls]
command = "simple-completion-language-server"
config = { max_completion_items = 20, snippets_first = false }

[language-server.scls.environment]
RUST_LOG = "debug,simple-completion-langauge-server=debug"
LOG_FILE = "/tmp/scls-completion.log"

[language-server.efm]
command = "efm-langserver"
config.documentFormatting = true

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]
config.hostInfo = "helix"

...

[[language]]
name = "typescript"
scope = "source.ts"
injection-regex = "(ts|typescript)"
file-types = ["ts", "mts", "cts"]
auto-format = true
language-servers = [
  { name = "efm", only-features = ["format", "diagnostics"] },
  { name = "typescript-language-server", except-features = ["format", "diagnostics"] },
  "scls",
  ]

[[language]]
name = "tsx"
scope = "source.tsx"
injection-regex = "(tsx)" # |typescript
file-types = ["tsx"]
roots = []
auto-format = true
language-servers = [
  { name = "efm", only-features = ["format", "diagnostics"] },
  { name = "typescript-language-server", except-features = ["format", "diagnostics"] },
  "scls",
]

```

3. try also config language server as
```toml
language-servers = [
  { name = "efm", only-features = ["format", "diagnostics"] },
  { name = "typescript-language-server", except-features = ["format", "diagnostics"] },
   { name = "scls"} ,
]
```

4. test snippet with 
```sh
simple-completion-language-server validate-snippets
2023-10-30T15:12:25.694782Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/pix/.config/helix/snippets/typescript.toml" for scope: Some(["typescript"])
2023-10-30T15:12:25.694942Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/pix/.config/helix/snippets/tsx.toml" for scope: Some(["tsx"])
2023-10-30T15:12:25.695001Z  INFO simple_completion_language_server::snippets::config: Try read config from: "/home/pix/.config/helix/external-snippets.toml"
2023-10-30T15:12:25.695039Z  INFO simple_completion_language_server: Successful. Total: 3
```

5. setup typescript.toml as
```toml
[[snippets]]
prefix = "rjus"
body = 'const [$1,set$2] = useState<$3>($4);'
scope = ["typescript","tsx"]

[[snippets]]
prefix = "cl"
body = 'console.log($1)'
scope = ["typescript","tsx"]
```

but when i type the prefix nothing happens...
what i'm missing?

Thanks

**Comment by estin** [comment]
Hi!

Please try to set  `scope = ["ts","tsx"]`

`scls` use scopes defined on [languges.toml](https://github.com/helix-editor/helix/blob/master/languages.toml#L635) and in yours settings for `typescript` scope is `scope = "source.ts"`. And `ts` would be used to filter snippets for current doc.

There helix docs about scopes https://docs.helix-editor.com/languages.html
```
scope - A string like source.js that identifies the language. Currently, we strive to match the scope names used by popular TextMate grammars and by the Linguist library. Usually source.<name> or text.<name> in case of markup languages
```

Hope this helps.

Another way to debug

a) Try to define snippets on file for all scopes `~/.config/helix/snippets/snippets.toml` and don't define scope for snippets

b) view logs on `/tmp/scls-completion.log`

**Comment by pix303** [comment]
Thanks for answering so quickly!
the only way it works is with solution a) (snippets/snippets.toml without scopes)

```sh
├── config.toml
├── languages.toml
└── snippets
    ├── snippets.toml
    └── ts.toml


2023-10-30T16:50:53.491196Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/pix/.config/helix/snippets/ts.toml" for scope: Some(["ts"])
2023-10-30T16:50:53.491303Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/pix/.config/helix/snippets/snippets.toml" for scope: None
```


maybe it`s a bad configuration of my language.toml?

**Comment by estin** [comment]
sorry... it's shame for me

`scope` in snippet definition it's language [identify](https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers)

and for `typescript` rigth scope is `typescript` as language_id

Right config is (don't set scope here)

```bash
$ cat ~/.config/helix/snippets/typescript.toml
```
```toml
[[snippets]]
prefix = "rjus"
body = 'const [$1,set$2] = useState<$3>($4);'

[[snippets]]
prefix = "cl"
body = 'console.log($1)'
```

```bash
$ cat ~/.config/helix/languages.toml
```

```toml
...
[[language]]
name = "typescript"
scope = "source.ts"
injection-regex = "(ts|typescript)"
file-types = ["ts", "mts", "cts"]
auto-format = true
language-servers = [
  "scls",
]
...
```

where `language_id` in `languages.toml` it's `language.name` https://github.com/helix-editor/helix/blob/master/helix-core/src/syntax.rs#L96

**Comment by pix303** [comment]
> sorry... it's shame for me

no problem at all 😄 

solutions found out as far are

```sh
├── languages.toml
└── snippets
    └── typescript.toml
```
without scope, but works only for .ts file, not for tsx

or
```sh
├── languages.toml
└── snippets
    └── snippets.toml
```
with scope `scope = ["typescript", "tsx"]`, but works only for .ts file, not for tsx

i've tried out without success `snippets/tsx.toml` (copy of typescript.toml)

**Comment by estin** [comment]
@pix303 can you update and try new version?

changed logic of  snippet `scope` overriding

**Comment by estin** [comment]
@pix303 
Hi! I will try it again. And can't reproduce issue.
All I can say now - try to simplify configs and note about `snippet.scope` it's list of `language_id`

By you config
```toml
[[language]]
name = "typescript"
scope = "source.ts"
injection-regex = "(ts|typescript)"
file-types = ["ts", "mts", "cts"]
auto-format = true
language-servers = [
  { name = "efm", only-features = ["format", "diagnostics"] },
  { name = "typescript-language-server", except-features = ["format", "diagnostics"] },
  "scls",
  ]

[[language]]
name = "tsx"
scope = "source.tsx"
injection-regex = "(tsx)" # |typescript
file-types = ["tsx"]
roots = []
auto-format = true
language-servers = [
  { name = "efm", only-features = ["format", "diagnostics"] },
  { name = "typescript-language-server", except-features = ["format", "diagnostics"] },
  "scls",
]
```

1) By configuring `~/.config/helix/languages.toml` you are create new or override default language declartion by `name` attribute as key. Docs https://docs.helix-editor.com/languages.html#languagestoml-files

2) Languages by you config has next `language_id`:
- for `tsx`  is [typescriptreact](https://github.com/helix-editor/helix/blob/master/languages.toml#L652)
- for `typescript`  is [typescript](https://github.com/helix-editor/helix/blob/master/languages.toml#L638)

Try to simplify `~/.config/helix/languages.toml`

```toml
[[language]]
name = "typescript"
language-servers = [
  { name = "efm", only-features = ["format", "diagnostics"] },
  { name = "typescript-language-server", except-features = ["format", "diagnostics"] },
  "scls",
]

[[language]]
name = "tsx"
language-servers = [
  { name = "efm", only-features = ["format", "diagnostics"] },
  { name = "typescript-language-server", except-features = ["format", "diagnostics"] },
  "scls",
]
```

define `ts`  snippets  `~/.config/helix/snippets/typescript.toml` like that 
```toml
[[snippets]]
prefix = "cl"
body = 'console.log($1)'
description = 'as ts snippet'
```

define `tsx`  snippets `~/.config/helix/snippets/typescriptreact.toml`  like that 
```toml
[[snippets]]
prefix = "cl"
body = 'console.log($1)'
description = 'as tsx snippet'
```

validate snippets
```bash
$ simple-completion-language-server validate-snippets
2023-11-01T16:08:43.568019Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/user/.config/helix/snippets/typescript.toml" for scope: Some(["typescript"])
2023-11-01T16:08:43.568067Z  INFO simple_completion_language_server::snippets::config: Try load snippets from: "/home/user/.config/helix/snippets/typescriptreact.toml" for scope: Some(["typescriptreact"])
2023-11-01T16:08:43.568096Z  INFO simple_completion_language_server::snippets::config: Try read config from: "/home/user/.config/helix/external-snippets.toml"
2023-11-01T16:08:43.568106Z  INFO simple_completion_language_server: Successful. Total: 2
```

check 

![ts](https://github.com/estin/simple-completion-language-server/assets/520814/0e8668b7-2031-40ae-a796-c6b0ddc30677)

![tsx](https://github.com/estin/simple-completion-language-server/assets/520814/7ffc0433-04fa-4657-bd4d-a8633d8ac7db)
